### ISSUE TITLE
Why do we try to twist UCUM parsing support for printing or vice versa?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#100]
This partly relates to https://github.com/unitsofmeasurement/uom-systems/issues/97

Why do we try to twist UCUM in ways it is not intended to be used?
http://unitsofmeasure.org/ucum.html#section-Grammar-of-Units-and-Unit-Terms speaks of 
> Therefore, any fully conformant parser 

The UCUM Essence file
https://github.com/eclipse/uomo/blob/master/examples/ucum/org.eclipse.uomo.examples.ucum.console/src/main/resources/ucum-essence.xml
calls just one attribute `printSymbol`.  The code atrributes are not necessarily meant for printing via `format()` or a similar method.

On the other hand nearly every table in the UCUM specification says
> Full name and print symbol are defined by ISO 1000 and are out of scope of The Unified Code for Units of Measure.

That means, UCUM doesn't really care about print symbol, it standardises **parsing** and that currently is known to work extremely well.
If you wanted to print say `POUND_FORCE` with a metric prefix like `KILO` using the `CASE_INSENSITIVE` variant, how should it look like?
"k[LBF_AV]", "[kLBF_AV]" or something else?

I think we try to force a catalog and definition to do something it is not meant to do.
Also creating another ticket for the display name (which again is not in scope of UCUM, but just a "nice to heave" feature of implementations)

**Comment by keilw** [comment]
If you try to parse() using the Print variant of UCUMFormat, you get a
```
new UnsupportedOperationException(
		    "The print format is for pretty-printing of units only. Parsing is not supported.");
```
I am not sure, if we should not do the same in` format()` for every variant other than `Print`.

**Comment by magnonasc** [comment]
You're saying here that `UCUM` isn't able parse using `Print` (it's a fact) and it shouldn't be able to format with `Print` aswell.. So you're saying that we should just delete the variant `Print`?

This really doesn't make any sense for me. Why would we delete something that's in the original docs?

**Comment by keilw** [comment]
No, but I'm questining, if the `format() `methods should be used for the C/I or C/S parsing codes. And throw an exception for those cases, trying to get format() done for the `Print` variant only. Otherwise the bracket and many other cases could be hard to solve.

**Comment by keilw** [comment]
It works reasonably well for CS and CI, so we can keep `format()` for all 3 flavors and `parse()` for all but `Print`.
