### ISSUE TITLE
Import package missing in MANIFEST.MF

### ISSUE THREAD

**Issue by duemila2** [unitsofmeasurement/uom-systems#102]
Dear all,
using this project bundle (_systems.uom:systems-common-java8_) in an OSGi environment we discovered that the instruction:
`Import-Package: tec.uom.se.format` 
was missing in the _MANIFEST.MF_ of s_ystems-common-java8-0.7.jar_ package.
The workaround used by us is wrapping the jar in a custom bundle that imports that package.
Best regards,
Roberto

**Comment by keilw** [comment]
Thanks will have a look for the next update release. @duckAsteroid Do you have an idea why it is missing?
