### ISSUE TITLE
Conversion bugs

### ISSUE THREAD

**Issue by frank-montyne** [unitsofmeasurement/uom-systems#103]
When I use UCUM and do a conversion from KELVIN to FAHRENHEIT I get a wrong result:
For example  273.15 KELVIN converts into -307.920 FAHRENHEIT. 

Looking into the getConverterTo function I saw the following:

- On the source unit we go from KELVIN to KELVIN so no converter
- On the target unit the FAHRENHEIT unit has a converter from KELVIN to FAHRENHEIT. That converter is returned but then inverted!
- That converter then gets concatenated with the source unit converter (that does nothing) 
- the result is the wrong conversion.

Can you have a look please?
Thanks,
Frank Montyne

**Comment by keilw** [comment]
According to UCUM these are "special units", which can have an impact on cnversion to other temperature units.

**Comment by frank-montyne** [comment]
I would assume a simple kelvin to fahrenheit conversion should always be
correct. What's the point of the library otherwise? Perhaps I don't really
understand what you are saying, can you elaborate a bit please?
Thanks,
Frank

**Comment by keilw** [comment]
See http://unitsofmeasure.org/ucum.html#section-Special-Units-on-non-ratio-Scales in the UCUM specification. Full UCUM implementations that pass its tests like UOMo UCUM cover these under https://github.com/eclipse/uomo/tree/master/bundles/org.eclipse.uomo.ucum/src/main/java/org/eclipse/uomo/ucum/special. The operation seems to combine two or more steps in the `UCUM ` class, so could you please try to reproduce the problem in https://github.com/unitsofmeasurement/uom-systems/blob/master/common/src/main/java/systems/uom/common/USCustomary.java?

Thanks,
Werner

**Comment by keilw** [comment]
It works with USCustomary, see https://github.com/unitsofmeasurement/uom-systems/blob/master/common-java8/src/test/java/systems/uom/common/ConverterTest.java

**Comment by keilw** [comment]
Should be fixed, there was a similar issue with `REAUMUR`, but both are addressed, see https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/test/java/systems/uom/ucum/ConverterTest.java
Thanks for raising the issue.

**Comment by frank-montyne** [comment]
Thanks!
