### ISSUE TITLE
Add Symbols for various UCUM Units

### ISSUE THREAD

**Issue by cacsar** [unitsofmeasurement/uom-systems#110]
In ucum-java8/src/main/java/systems/uom/ucum/UCUM.java it appears that the units in UCUM are defined without any symbols being set, this would appear to prevent parsing of compliant representations and reasonably expected representations of units being prepared.

If there isn't anything blocking it besides doing the work that would be great to know.

**Comment by keilw** [comment]
I guess you mean their representation using `toString()` or `SimpleUnitFormat`?
That is possible, given the primary focus of the UCUM units and module is to work as close as possible to the UCUM spec and catalog, therefore it comes with a dedicated `UCUMFormat` for all the 3 variants. I highly doubt, you'll find any of them missing using that UnitFormat, but it is quite likely those that are not derived from another system could be missing SimpleUnitFormat support. There is no reason against that, just someone has to implement it ;-)
