### ISSUE TITLE
Adjust UCUMConverterFormatter for Indriya 2

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#128]
The JSR 385/Indriya 2 based Prefix implementations use different UnitConverter implementations, UCUMConverterFormatter is not adjusted to handle e.g. PowerOfIntConverter, so correct but ugly fallback formatting like "g.1000" instead of "kg" occurs.

**Comment by andi-huber** [comment]
Now solved with #146 ?

**Comment by keilw** [comment]
I hope so, are there JUnit tests to back it?

**Comment by andi-huber** [comment]
I've put some tests in place with #146 (those I've listed in the issue's description). But we might need more, or some sophisticated Test to check for *all* the predefined prefixes.

**Comment by keilw** [comment]
I hope so, as there is no `PowerOfIntConverter`, I guess we can close it.
