### ISSUE TITLE
parsing of imperial units

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-systems#129]
Hi again, 
    I'm again lost with some small problems of parsing, in particular I'm trying to parse "miles" and, even using the `systems.uom.common.internal.CommonServiceProvider` (which I see uses `SimpleUnitFormat`). 

I always get the exception `javax.measure.format.ParserException: Parse Error`. 

Perhaps I'm doing something wrong, is it correct to try to use the commonService provider to do so? 

Thank you in advance
Luca

**Comment by keilw** [comment]
Is it the exact word "miles" you try to parse?

**Comment by lfoppiano** [comment]
Hi @keilw, I've tried `miles`, `pounds` and `mi`

**Comment by keilw** [comment]
Actually there is no `MILE` in the `Imperial` system. `USCustomary` should contain it, there it's labelled with `SimpleUnitFormat`.

**Comment by lfoppiano** [comment]
> Actually there is no `MILE` in the `Imperial` system. `USCustomary` should contain it, there it's meant to be labelled with `SimpleUnitFormat`.

I'm not sure I understand this. What should I use then? 

> Did you use the most recent versions? 0.9 of systems-common or the 1.0-SNAPSHOT?

I'm using version 0.9. Should I move to the SNAPSHOT?

**Comment by keilw** [comment]
Yes please, the https://github.com/unitsofmeasurement/uom-demos/blob/master/console/systems/common/src/main/java/tech/uom/demo/systems/common/CommonFormatDemo.java parses both "mi" and after calling `SimpleUnitFormat.alias()` also "mile" without problems.

**Comment by lfoppiano** [comment]
@keilw looking at your example I'm wondering why do we need to manually create the alias of miles? is not included in any format / parsers by default?

**Comment by keilw** [comment]
No it's not included because it is custom specific right now.

**Comment by lfoppiano** [comment]
Hi @keilw,
    When I call `alias()` it will be applied then to all the instances of SimpleUnitFormat? 

I have been thinking to ask this already some time ago... I would need some review / feedback on this. I find difficult to still grasp the way I should best implement the `unit of measurement` in my application. If you prefer I could move to another issue this question...  

I'm implementing the parsing by instantiating several `UnitFormatServices` in the constructor (see full code: https://github.com/kermitt2/grobid-quantities/blob/master/src/main/java/org/grobid/core/data/normalization/QuantityNormalizer.java) and try them in sequence (see method `tryParsing` in the same file). 
```
ServiceProvider defaultProvider = ServiceProvider.current(); // just a fallback to avoid uninitialized variable
        for (ServiceProvider provider : ServiceProvider.available()) {
            UnitFormatService formatService = provider.getUnitFormatService();
            switch (provider.getClass().getName()) {
                case "tec.uom.se.spi.DefaultServiceProvider":
                    this.defaultFormatService = formatService.getUnitFormat();
                    break;

                case "systems.uom.ucum.internal.UCUMServiceProvider":
                    this.ucumFormatService = formatService.getUnitFormat();
                    break;

                case "systems.uom.unicode.internal.UnicodeServiceProvider":
                    this.unicodeFormatService = formatService.getUnitFormat();
                    break;

                case "si.uom.impl.SIServiceProvider":
                    this.siFormatService = formatService.getUnitFormat();
                    break;

                case "systems.uom.common.internal.CommonServiceProvider":
                    SimpleUnitFormat.getInstance().alias(USCustomary.MILE, "mile");
                    this.commonService = formatService.getUnitFormat();
                    break;

                case "tec.units.indriya.spi.DefaultServiceProvider":
                    this.indyriaDefaultService = formatService.getUnitFormat();
                    break;

                case "tech.uom.seshat.UnitServices":
                    this.seshatUnitServices = formatService.getUnitFormat();
                    break;
            }
        }
```

I'm wondering, if all these are sharing the same SimpleUnitFormat implementation, maybe it does not make sense to instatiate them at all... isn't it? Or maybe I should load the different flavours (case sensitive, case insensitive, etc...)? 

What do you think?

**Comment by lfoppiano** [comment]
Again me, I've also noticed that the class `systems.uom.ucum.format.UCUMFormat$Parsing` is parsing `yd` (`yards`) to `yday` -> `day`

**Comment by keilw** [comment]
Please raise a separate issue about the last point, if "yard" really gets misinterpreted with "day" in  `UCUMFormat`, we should look into that. 

For everything else, I guess it could be more of a case for uom-demos. Note, while modules like `systems-common-java8` (legacy if you want) use `uom-se` and may still require the kind of `if/else` or `switch` statements, the new `ServiceProvider.of()` method in Unit-API/Indriya 2.x allows to directly retrieve a registered `ServiceProvider` by name, thus saving a lot of that boiler-plate code.

**Comment by lfoppiano** [comment]
Thanks @keilw regarding the best practices, usage maybe we can discuss on gitter

**Comment by keilw** [comment]
Sure, if this results in something for the [UoM Guidebook](https://github.com/unitsofmeasurement/uom-guide), everyone is more than welcome to help with that.

**Comment by lfoppiano** [comment]
Perfect for me. :-)
