### ISSUE TITLE
Conversion of 'h' 

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-systems#132]
HI all, 
  I'm having a weird behaviour, when I try to convert `hours` / `h` in their base unit `seconds`. 

If I use the UCUM converter, I get it correcty, but with the other conversers
 - ﻿Unicode service provider
 - SI service provider
 - DEfault service provider 

I get the unit parsed correctly but having the system Unit `J·s`, which is the Planck constant (http://ckw.phys.ncku.edu.tw/public/pub/Notes/PhysicalConstants/Fundamental%20Physical%20Constants.htm) ... let's say I know this is `hours` is there a way to help/customise the normalisation? 

Maybe I'm missing also how I should be implementing this part, thanks in advance for your advices. 
Luca

**Comment by lfoppiano** [comment]
HI all, 
 again me. I'm back to this issue again, since after updating to `2.0-SNAPSHOT` it seems that every default unit format, converts `h` to the `PLANCK_CONSTANT`. 

I've tried to debug and trying to understand where the problem is, I notice that 

```
@Override
    public void label(Unit<?> unit, String label) {
      if (!isValidIdentifier(label))
        throw new IllegalArgumentException("Label: " + label + " is not a valid identifier.");
      synchronized (this) {
        nameToUnit.put(label, unit);
        unitToName.put(unit, label);
      }
    }
```

inside SimpleUnitFormat.java (indriya) is called twice, and the `h` (time) is overriden by the plank constant. 

Line 239 of UCUM.java: `public static final Unit<Time> HOUR = addUnit(Units.HOUR);`
Line 282 of UCUM.java: `public static final Unit<Action> PLANCK = addUnit(SI.JOULE_SECOND.multiply(6.6260755E-34));` 

could that be the case that the definition of `h` is overwritten?

**Comment by keilw** [comment]
Actually it's not "h", it's "ℎ" for the Planck constant.

**Comment by lfoppiano** [comment]
> Actually it's not "h", it's "ℎ" for the Planck constant. It's already addressed in the 2.0-SNAPSHOT of SI Units, guess a few errata will also go into the 1.x branch soon after.

OK, but I was talking about `2.0-SNAPSHOT`. I will have a look closely...

**Comment by keilw** [comment]
@lfoppiano is this still an issue or could it be closed?

**Comment by lfoppiano** [comment]
@keilw give me some time to check and I will either close or reply here.
