### ISSUE TITLE
UCUMFormat is not correctly appending superscript powers when formatting units 

### ISSUE THREAD

**Issue by mattdehring** [unitsofmeasurement/uom-systems#135]
If a unit like m3/s is input the output is m/s3 instead. It also appears that if there are multiple units in the denominator it doesn't correctly add parenthesis around them. For instance if you have an input of m/(s.bar) the output is m/s/b.

**Comment by mattdehring** [comment]
I made a PR that has unit tests for the problems and a solution for it

**Comment by cleberecht** [comment]
I just run into the same problem. Thanks for the fix.

**Comment by alexanderkiel** [comment]
Unfortunately you introduced a new bug with commit 2fdd93da6c. `kg/m2` formats to `kg/m` now. The fix is simple, you just have an `Math.abs` too much. You can find it here:

https://github.com/unitsofmeasurement/uom-systems/blob/6ba1e8b0a0cba6764a5189d21fa4d550b3cb9b92/ucum-java8/src/main/java/systems/uom/ucum/format/UCUMFormat.java#L253

**Comment by keilw** [comment]
That does not seem new with 1.0 though which only incorporates SI 1.0, could you propose a line instead of `if (Math.abs(u.getValue()) < -1){` that fixes the issue in your experience or propose a PR?

**Comment by alexanderkiel** [comment]
Thanks @keilw @mattdehring I decided agains a PR because I don't oversee all locations it has to be fixed.

**Comment by keilw** [comment]
So without the abs(), we'll try that. Because the SI redefinition affects the SI system modules and probably in some cases also UCUM directly, we expect one or the other update in the 1.x branch independent of the 2.x (master) branch.

**Comment by alexanderkiel** [comment]
Would you recommend to use the 2.x branch instead? I remember having some problems using the whole 2.x system. But not exactly how. I only need to parse and format unit and quantities for calculation.

**Comment by keilw** [comment]
2.0 of Unit-API is not final yet, but if you are fine with a SNAPSHOT release, it works and will be the one taking over soon.

**Comment by alexanderkiel** [comment]
Ok thanks. Now I understand. No, I can't use a SNAPSHOT.

**Comment by keilw** [comment]
Great, than please use 1.x at least till around late Q2, then all 2.x versions based on Indriya 2 Final and JSR 385 should be available. And if you used uom-se or the -java8 variants, those work on identical environments. The minimal JRE should be Java SE 8 in most cases, on occasion we might raise it to 9-11, especially if new features are used like JShell.

**Comment by alexanderkiel** [comment]
Thank you a lot. I use 1.x in -java8 variant with Java SE 8 but might be update to Java SE 11 later this year.

**Comment by zmcode** [comment]
Hello, is there any news about this issue? I am using version 2.0 (not snapshot) and `UCUMFormat.getInstance(UCUMFormat.Variant.CASE_SENSITIVE).format(UCUM.GRAM.divide(UCUM.METER.pow(3)))` produces `g/m` instead of `g/m3`.

**Comment by keilw** [comment]
As demonstrated in UCUMFormatDemo of the UCUM console demos, this was fixed by #162 in 2.0.2, please test the SNAPSHOT, we plan to release it soon.
