### ISSUE TITLE
2.0 Version Setup and US units

### ISSUE THREAD

**Issue by mcatflex** [unitsofmeasurement/uom-systems#155]
Hi folks, I am trying to use the unit api for conversions between metric and US units. I was having trouble trying to figure this out. I tried to add this repo (uom-systems) to my build.gradle but encountered an issue when trying to build.

**build.gradle**

```
implementation "javax.measure:unit-api:2.0"
implementation "tech.units:indriya:2.0.1"
implementation "systems.uom:systems-parent:2.0"
```

The issue is that gradle "Could not find tech.uom:uom-parent:2.0.1". The latest version of tech.uom:uom-parent on [mvnrepository is version 2.0](https://mvnrepository.com/artifact/tech.uom/uom-parent/2.0).

Let me know if that version needs to be added or changed. Additionally, let me know if this repository is the correct one to use to add US and Imperial units. Thanks!

**Comment by keilw** [comment]
I just asked Bintray to sync it, I was under the impression, it had already happened, should be there within a few hours. Please try it then or add JCenter to your Gradle setting, then it would work right now.

**Comment by keilw** [comment]
This should work now: https://search.maven.org/artifact/tech.uom/uom-parent/2.0.1/pom Closing it, please reopen or create a new one if you face any further problems.
