### ISSUE TITLE
Complex Unit Support (Volume related to temperature)

### ISSUE THREAD

**Issue by expertalex** [unitsofmeasurement/uom-systems#176]
Thanks a lot for your workI The API Design is amazing and I was interested on it and sow that Volumes and Weights are not linked to Temperature.

For example We Sometimes want to Convert Between Liters at 15 Degrees to Galons at 50 Degrees for a particular substance. 

Is your Framework designed to add relationship between Base Units? Or can we creare more advanced units based on the API?

CompexVolume = { Volume and Temperature }

See: When is a Litre not a Litre?
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/283253/laymans-guide-on-sta-measurement-v2-march_2011.pdf

**Comment by andi-huber** [comment]
Please note the distinction: 1 **litre** of water has different mass depending on temperature (and pressure). But 1 **litre** understood as volume in physical space does not change with temperature! So there is no such thing as _TemperatureVolume_. (At least that does not make any sense to me.) To model your use-case consider to work with mass and density of water  (or whatever material you are interested in) and derive the volume from that.

**Comment by keilw** [comment]
Thanks, then I think we can close that becasue Torque is already defined. Everyone feel free to open another ticket if you feel a quantity or something else was mising.
