### ISSUE TITLE
Dimension of BEL_WATT and BEL_KILOWATT is wrong

### ISSUE THREAD

**Issue by frank-montyne** [unitsofmeasurement/uom-systems#178]
The dimension of BEL_WATT and BEL_KILOWATT should be level of power instead of level of electric potential.
It is stated correctly in the comments but wrongly defined:

```
/** power level */
public static final Unit<Level<ElectricPotential>> BEL_WATT = addUnit(
	 WATT.transform(new LogConverter(10)).asType(Level.class));

public static final Unit<Level<ElectricPotential>> BEL_KILOWATT = addUnit(
	 KILO(WATT).transform(new LogConverter(10)).asType(Level.class));

```
should be:
 
   ```
public static final Unit<Level<Power>> BEL_WATT = addUnit(
	 WATT.transform(new LogConverter(10)).asType(Level.class));

   public static final Unit<Level<Power>> BEL_KILOWATT = addUnit(
	 KILO(WATT).transform(new LogConverter(10)).asType(Level.class));

```

See also [Finnish thesaurus and ontology service: ucum](https://finto.fi/ucum/en/page/r426)

**Comment by keilw** [comment]
Seems a copy/paste mistake from BEL_VOLT. Thanks for spotting that. You are welcome to create a PR if you can, otherwise we plan to fix that with the 2.1 release train which is supposed to follow that of the main JSR deliverables like API, RI or TCK in Q4.

**Comment by frank-montyne** [comment]
I just created a PR.

**Comment by keilw** [comment]
I'll check it out, thanks. Especially in UCUM we have a contributors file, would you like to be mentioned there?

**Comment by frank-montyne** [comment]
Maybe next time, this was a really small thing...

Best regards,
Frank
