### ISSUE TITLE
comparable units should be reduced on division

### ISSUE THREAD

**Issue by VladimirAlexiev** [unitsofmeasurement/uom-systems#182]
I use UCUM on the semantic web through LINDT (https://github.com/OpenSensingCity/jena-ucum by @maximelefrancois86, @Antoine-Zimmermann).

I'm trying to find the conversion factor of `LB-PER-H` for https://github.com/qudt/qudt-public-repo/issues/285 (@steveraysteveray).
I tried this query at https://ci.mines-stetienne.fr/lindt/playground.html:

```sparql
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
select ("1 [lb_av]/h"^^cdt:ucum / "1 kg/s"^^cdt:ucum as ?conv) {}
```

The result is `"1.0 s.[lb_av]/h/kg"^^cdt:dimensionless`.
This might be formally correct but is highly useless: I expect to get `0.00012599803` or `0.00012599803^^xsd:double` or as last resort `"0.00012599803"^^cdt:dimensionless` (or a number approximately equal to this).

I'm posting this here (@keilw, @magnonasc) instead of `jena-ucum` because I guess it comes from the core java-ucum engine.

**Comment by VladimirAlexiev** [comment]
Why is this important: `java-ucum` includes a bunch of conversion factors and this is the most natural way to get them out.

We have a big discussion at https://github.com/w3c/sparql-12/issues/129 whether UoM factors should be used as encoded in Java (LINDT), or should be explicitly put into triples (QUDT), and being able to get it out of `java-ucum` will provide a bridge.

**Comment by keilw** [comment]
No it has nothing to do with that "Core Java UCUM Engine" wich came out of [UOMo UCUM](https://github.com/eclipse/uomo/tree/master/bundles/org.eclipse.uomo.ucum) a project I maintained many years ago and still keep it alive, but it is of lesser priority right now.

So I'll close this ticket, please raise them with the `java-ucum` project.

**Comment by VladimirAlexiev** [comment]
@keilw Could you kindly point me to that repo? I [searched for java-ucum](https://github.com/search?q=java-ucum) and I only find https://github.com/FHIR/Ucum-java, which is probably not it.

**Comment by keilw** [comment]
With @grahamegrieve it sounds a lot like it, he was also a main contributor behind the UOMo UCUM bundle some years ago.
