### ISSUE TITLE
Is this project using the UCUM system?

### ISSUE THREAD

**Issue by ppazos** [unitsofmeasurement/uom-systems#197]
https://ucum.org/

I'm wondering because the readme doesn't have info about UCUM and this project seems to be an implementation of what the UCUM spec defines. Thanks.

**Comment by keilw** [comment]
Mostly on the top level [readme](https://github.com/unitsofmeasurement/uom-systems), but there is also one in the UCUM folder

**Comment by keilw** [comment]
I trust this answered your question @ppazos, closing this ticket. Feel free to open another one with further questions.
