### ISSUE TITLE
java.lang.Short supplied to Quantities

### ISSUE THREAD

**Issue by bahrigencsoy** [unitsofmeasurement/uom-systems#29]
Hi,

I have found this issue in reference implementation but unable to submit an issue to that project, sorry for the inconvenience I cause.

I have noticed that supplying short instance to Quantities will result in an unexpected behaviour.

I have an ad-hoc Angle type, coming from an embedded system. It fits into signed 16 bit (short) and linearly converted to degrees. The conversion is simple ax+b equation which I defined for radians as follows:

```java
adhocRads = new TransformedUnit<>(Units.RADIAN, new AddConverter(0.00004793773773)
                .concatenate(new PiMultiplierConverter().concatenate(new RationalConverter(2, 65535))));
```

The unit test below for this type runs if integer is supplied, but fails with "short":

```java
public class AdhocRadianTest {

    private TransformedUnit<Angle> adhocRads;

    @Before
    public void setUp() throws Exception {
        adhocRads = new TransformedUnit<>(Units.RADIAN, new AddConverter(0.00004793773773)
                .concatenate(new PiMultiplierConverter().concatenate(new RationalConverter(2, 65535))));
    }

    @Test
    public void testWithInteger() {

        Quantity<Angle> minusPiRadian = Quantities.getQuantity(-Math.PI, Units.RADIAN);

        Quantity<Angle> leftEnd = Quantities.getQuantity(-32768, adhocRads);

        assertEquals(minusPiRadian.getValue().doubleValue(), leftEnd.to(Units.RADIAN).getValue().doubleValue(),
                0.0000001);

    }

    @Test
    public void testWithShort() {

        Quantity<Angle> minusPiRadian = Quantities.getQuantity(-Math.PI, Units.RADIAN);

        Quantity<Angle> leftEnd = Quantities.getQuantity(Short.MIN_VALUE, adhocRads);

        assertEquals(minusPiRadian.getValue().doubleValue(), leftEnd.to(Units.RADIAN).getValue().doubleValue(),
                0.0000001);

    }

}
```

With significant difference:

> java.lang.AssertionError: expected:<-3.141592653589793> but was:<-3.417774230990417E8>
> 	at org.junit.Assert.fail(Assert.java:88)
> 	at org.junit.Assert.failNotEquals(Assert.java:834)
> 	at org.junit.Assert.assertEquals(Assert.java:553)
> 	at org.junit.Assert.assertEquals(Assert.java:683)
> 	at net.gencsoy.units.AdhocRadianTest.testWithShort(AdhocRadianTest.java:48)
>         ...
>

**Comment by keilw** [comment]
There is no backing type `ShortQuantity` in the RI (nor in uom-se) so thanks for the ticket here. If a JIRA issue is required for the RI we'll create a "proxy" pointing to this one.
