### ISSUE TITLE
disabiguation of units with the same notation (e.g. pH Acidity vs picoHenry )

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-systems#30]
Hi, 
   we need to be able to normalized the unit pH. Thanks to @keilw (see [here](https://github.com/unitsofmeasurement/uom-se/issues/126)) I've been pointed to this project. 
Though there is some documentation, it is not fully clear what is the relationship betweeen this project and the uom-se. Is uom-se an implementation of part of the units which this project supports? 

The problem is the following, if I want to parse the unit pH (as acidity measurement), using the uom-se SimpleUnitParser I'm getting picoHenry, which makes sense somehow. 

Assuming there is a way to have the type of measurement, for example in the case of pH, we have the tuple (pH, acidity-nonSI), then we can select correctly the parser. I've looked up for pH (as acidity measurement) and seems not present yet. 
How should be added? 

On the other hand, I've noticed also that in case of considering acidity (pH) as a base unit (it is correct?), the QuantityDimension cannot currently be used, because it supports only a constructor acceptin a single character: 
```
public QuantityDimension(char symbol) {
```

I'm sorry if this post is a bit confused, I'm a bit lost on finding the way things should be done properly. 

Thanks for your help. 
Luca

**Comment by keilw** [comment]
I saw a discussion about it and they recommend treating pH as a `Dimensionless` unit. UCUM http://unitsofmeasure.org/ucum.html should handle that already (assuming our system is complete and pH wasn't added more recently) and it only gets parsed as [pH] (or [PH] in the context-insensitive version) while pH would be "Pico-Henry" as mentioned ;-) You can always "patch" `SimpleUnitFormat` for your needs via `UnitFormat.label()`, but for other systems like ISO80000 let's see. 
One approach could be similar to UCUM. Look at https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/main/java/systems/uom/ucum/format/UCUMFormat.java you'll notice, there are variants like "Print" or "Contextsensitive". So for ISO80000 one could even think of subsystems like "ISO80000-9" and provide the necessary "ISO80kUnitFormat" instances. Where they are static and not dependent on e.g. a locale https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/spi/UnitFormatService.java already has the necessary accessor so you'd call `UnitFormat getUnitFormat(String name)` along the lines of :
`UnitFormat iso8k9Format = unitFormatService.getUnitFormat("ISO80000-9");`

**Comment by keilw** [comment]
There's potentially need in both ISO and UCUM systems. Hence I added labels equivalent to "Component" in JIRA. Please feel free to propose a PR under this ticket. Even http://unitsofmeasure.org/ucum.html §45 covering e.g. "pH" is mostly missing in the current "static" UCUM system (a dynamically parsed one in Eclipse UOMo should cover everything in ucum-essence.xml, there is another ticket here to add similar functionality if we want) Same for ISO 80000. The full content of each of those is mostly available to those who pay ISO for their documents. Therefore I can't say, if we can make all of that available free and Open Source, have to check with ISO organization and site first. UCUM is open and freely available, so go for it there at any time.

**Comment by keilw** [comment]
See http://www.iso.org/iso/home/store/licence_agreement.htm we'll have to revisit the ISO80000 module I'm afraid. Go ahead with UCUM since it is an openly available free catalog, so as long as one doesn't violate its license terms (http://unitsofmeasure.org/trac/wiki/TermsOfUse) anybody may use and publish the catalog. That is not the case with ISO, thus we'll have to discontinue the ISO module at least in its free, Open Source form
