### ISSUE TITLE
Strange output when converting meters to inches

### ISSUE THREAD

**Issue by DeepSnowNeeL** [unitsofmeasurement/uom-systems#41]
Hello, I was trying to give a shot at converting units with this implementation and ran into this behavior :

```java
Quantity<Length> quantity = Quantities.getQuantity(5, Units.METRE);
Unit<Length> centi = MetricPrefix.CENTI(Units.METRE);
System.out.println(quantity.to(centi));
System.out.println(quantity.to(Imperial.INCH));
System.out.println(Imperial.INCH.getName());
System.out.println(Imperial.INCH.getSymbol());
```

Which outputs :
>500.0 cm
>196.8503937007874 m*127.0/5000.0
>null
>m

Is this normal ? What do I need to edit so it outputs "in" instead of the calculation on meter ? How to get the correct name of the INCH unit ?

Thanks

**Comment by keilw** [comment]
Thanks for raising it, we'll work on your ticket. The `label()` method is probably missed for a few. Will look into it as soon as we can (at the latest Hackergarten at JavaOne, but could be sooner)

Cheers,
Werner

**Comment by DeepSnowNeeL** [comment]
Is it fixed ? Is it released on maven central ? Thanks

**Comment by keilw** [comment]
Yes, 0.5 which also got full OSGi support has this fixed. Based on further updates to the SI system, there should be a 0.5.1 very soon with further improvements. 
In all relevant cases toString() should work via the labels applied. Some units got a name, too. The symbol as http://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/Unit.html#getSymbol() explains in many cases doesn't have a value, e.g. for product units, etc. A majority of units you find in US or Imperial and other systems are derived units, so they rarely have a symbol or you may find the symbol of the underlying base unit for certain derived units. So label() and toString() help to apply human readable representations of the unit. Especially the default formatters use that.
