### ISSUE TITLE
PiMultiplierConverter loops infinitely

### ISSUE THREAD

**Issue by krevelen** [unitsofmeasurement/uom-systems#46]
Both these conversions loop infinitely, somewhere during execution of `tec.uom.se.function.PiMultiplierConverter.Pi#arccot(BigDecimal, int)`:

- `Quantities.getQuantity( BigDecimal.ONE, Units.DEGREE_ANGLE ).to( Units.RADIAN )`
- `Quantities.getQuantity( BigDecimal.ONE, Units.RADIAN ).to( Units.DEGREE_ANGLE )`

Perhaps I should create my own `DEGREE_ANGLE` unit with a `PiMultiplierConverter` based on e.g. [Apfloat Pi calculators](http://www.apfloat.org/apfloat_java/docs/org/apfloat/samples/Pi.html), or do you have other suggestions?

**Comment by keilw** [comment]
Did you only face this in UoM-SE or both that and the RI?

**Comment by keilw** [comment]
I checked Apfloat and it seems to use the  GNU Lesser General Public License, so not a good candidate to use in either or our libraries I'm afraid (all BSD, we would not want to get any GPL stuff other than that in the JDK ;-) but if that's not an issue in your own app and implementations, feel free to use it.
