### ISSUE TITLE
SimpleUnitFormat produces uninformative error message

### ISSUE THREAD

**Issue by krevelen** [unitsofmeasurement/uom-systems#49]
`tec.uom.se.format.SimpleUnitFormat.DefaultFormat#check(boolean, String, CharSequence, int)` seems to invoke an incorrect constructor for `javax.measure.format.ParserException`, as the `ParserException#getMessage()` returns just an uninformative `"Parse Error"`, whereas the `ParserException#getParsedString()` returns an error message rather than the expected `String` being parsed, e.g:
```java
tec.uom.se.quantity.Quantities.getQuantity("300 d");
```
...throws an `IllegalArgumentException` with its cause `ParserException#getParsedString()` returning `"d not recognized (in 300 d at index 4)"`

**Comment by keilw** [comment]
This is does not belong here, created https://github.com/unitsofmeasurement/uom-se/issues/133
