### ISSUE TITLE
Make UCUMFormatService available in ServiceProvider

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#63]
The `UCUMFormatService `should also be available via `ServiceProvider`

**Comment by keilw** [comment]
Blocked by https://github.com/unitsofmeasurement/uom-se/issues/148. So requires uom-se 1.0.5 at least SNAPSHOT.

**Comment by magnonasc** [comment]
Hey @keilw, is this a `help wanted` issue, or will you fix this one?

**Comment by keilw** [comment]
@magnonasc Thanks, I can fix that. It depends on uom-se 1.0.5 first, so getting that out first.

**Comment by magnonasc** [comment]
So, I only need to create more tests (and fix the bugs if any) and then introduce those units that are in block of comments, the it'll be ready :)

**Comment by magnonasc** [comment]
So, wasn't it fixed? @garretwilson tried to use the `ServiceProvider` as you can see in #94 and it broke, if it wasn't, why was this issue closed? If it was, what happened to that?
