### ISSUE TITLE
UCUMFormat cannot parse (certain) units with a prefix

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#64]
parsing "km" e.g. `TestUnitJacksonModule.testParseLengthKm()` in https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure currently fails with a `TokenException`.

**Comment by keilw** [comment]
Use https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure/issues/3 to verify if addressed

**Comment by magnonasc** [comment]
Heey @keilw, how do we parse a unit with the prefix `MICRO`? I get an error with anything I try, even if I copy and paste the character used on the class `MetricPrefix`.

**Comment by magnonasc** [comment]
This issue seems okay, if there's another bug we might be able to find this out after working on #81.
