### ISSUE TITLE
Verify the current implementation of UCUM and bring comments up-to-date

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-systems#65]
The UCUM version being used on this implementation is 1.9, and as UCUM is on its 2.0.1 version there is a need to check for changes and fix the comments with missing sections (e.g., `TYPESETTER'S LENGTH UNITS: UCUM 4.4 §39` which now is §42) to make it easier to look for them on UCUM documentation when working on #59.

**Comment by magnonasc** [comment]
In `public static final Unit<Action> PLANCK = addUnit(SI.JOULE_SECOND.multiply(6.6260755E-24)); 
//FIXME get rid of JXQ import (where from??)` on `UCUM` class, how does this error relates to the wrong value that should be `6.6260755E-34` instead of `6.6260755E-24`? Or where you referring to something else? It seems that the build is still okay after fixing that, what makes me confused about your comment.

**Comment by keilw** [comment]
I cannot exactly point JXQ to anything still in the current code. It may have been from JScience or an earlier codebase. Should be safe to drop the comment.

**Comment by magnonasc** [comment]
Okay, so I'll just fix the wrong value and drop the comment... Feel free to assign this issue to me as I'm working on that already.

**Comment by magnonasc** [comment]
Just some typos and two errors were found as part of this issue, the others are just missing and might be added as part of #59.
