### ISSUE TITLE
Modify DEGREE to the UCUM definition

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#77]
Currently UCUM.DEGREE reuses units that shall be in NonSI (because they are not SI standard units) but the JavaDoc states
```
	 * We deviate slightly from the standard here, to maintain compatibility
	 * with the existing NonSI units. In UCUM, the degree is defined as
	 * <code>PI.multiply(RADIAN.divide(180))</code>.
```
Shouldn't this be consistent inside UCUM? Otherwise using it with parsers based on the ucum-essense there would be a mismatch.

**Comment by magnonasc** [comment]
Well, if it's not consistent we'll make it consistent :) I'll start working on that.

**Comment by magnonasc** [comment]
Should I make this change to all the other deprecated units?

**Comment by keilw** [comment]
Yes but only in UCUM please! They may be defined differently in Unicode or si-units. If different unit systems use different factors despite a similar or identical name, that can always happen, but ideally the strongly typed UCUM system should match the dynamically typed UCUM parsers like in UOMo where the XML definitions are used.

**Comment by keilw** [comment]
We cannot use the Wildcard, that bothers Java 8 compiler, so as of now I defined `NEPER `as `Unit<Level<Dimensionless>>>`.  In the constant definition unlike some operations the wildcard is not allowed.

**Comment by magnonasc** [comment]
So `NEWTON_CONSTANT_OF_GRAVITY` and `BOLTZMAN` needs to be updated too.
