### ISSUE TITLE
Set an expected UCUM release date

### ISSUE THREAD

**Issue by apatzer** [unitsofmeasurement/uom-systems#84]
Some of us are pretty excited to see UCUM supported in this repository. Any planned release date to Maven?

**Comment by keilw** [comment]
At the moment we're aiming for end of March, see https://github.com/unitsofmeasurement/uom-systems/milestone/3. Will have to check with those helping, if that's feasible. Should not take much longer I assume, if anything was missing or can be improved, we could certainly do 0.7.x updates.

**Comment by garretwilson** [comment]
If most of the UCUM stuff is ready by the 0.7 milestone, and if @magnonasc thinks it's feasible, I would prefer to have UCUM support included in 0.7 and then provide improvements in 0.7.x updates as @keilw  suggested. At least that way people will have something to use going forward; currently we don't even have short-term solutions other than hard-coding some conversions. I think getting a first version out, even if not 100% complete, will be a big step.

@magnonasc do you have any thoughts on this?

**Comment by magnonasc** [comment]
I agree that it would be good to present `UCUM` on next release, the biggest issue is to make the prefix `MICRO` work properly (as part of #64), after that we might have the base for a functional `UCUM` implementation.

**Comment by keilw** [comment]
Still a few issues to look into. 0.7 requires uom-se 1.0.5 out first, so let's give it another week.

**Comment by keilw** [comment]
Looks like all the remaining issues are low-hanging fruits. Activating UnitFormatService relies on uom-se 1.0.5, but that should be out between tonight and tomorrow night.

**Comment by garretwilson** [comment]
I have a client project I need to release as v1.0.0 by the end of this week, so I'm crossing my fingers that `uom-systems` gets released in the next day or two so I can remove my kludge workaround and switch to full UCUM support before the release. Good luck, guys!

**Comment by keilw** [comment]
Yes, don't worry. I think there is no showstopper and all tests added feel like 0.7 is good to be released. It only requires a quick update to si-units first, because of the underlying uom-se version (we don't want them to divert, that can have nasty side-effects) So tonight SI Units go out. And no later than tomorrow Unit Systems shall follow (once SI is in JCenter it could even be a little sooner)
