### ISSUE TITLE
Make the name of variable for velocity of light consistent

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-systems#86]
Although `C` was adopted to refer to velocity of light, which is understandable, I think it wasn't the best approach, because `C` is the symbol representing the `Coulomb` unit, and if we make the name of variables reflect to the name of the unit in `UCUM` specification we should make it consistently to everything.

The unit for velocity of light is the only one that a symbol was adopted to be its name, and if someone tries to use your api based upon the `UCUM` specs would it be clear at all?

**Comment by magnonasc** [comment]
@keilw, if you have a reasonable reason for having `C`, let me know, and you can deny this pull request without any problem.

**Comment by keilw** [comment]
https://en.wikipedia.org/wiki/Speed_of_light states
>The speed of light in vacuum, commonly denoted c

But of course why not adjust to the UCUM term "velocity of light"

**Comment by desruisseaux** [comment]
The speed of light is commonly denoted c, but this is the name of the variable used in equations, not the unit of measurement.

**Comment by keilw** [comment]
Thanks, I assume consistency with the UCUM catalog makes sense where it's possible (e.g. no redundant entries;-)
