### ISSUE TITLE
Add contributors.txt file.

### ISSUE THREAD

**Issue by garretwilson** [unitsofmeasurement/uom-systems#89]
I'm so excited that a UCUM implementation of JSR 363 will soon be available. I'm needing it urgently for a project I'm working on, and I know that many people around the world will also be glad to have one available.

I'm happy that @keilw let @magnonasc and me (Magno is doing most of the actual work) help complete the UCUM implementation. I want to make sure @magnonasc  gets the credit he deserves for his contribution, and I'd like to make sure my company GlobalMentor, Inc. gets a little mention as well, since it's contributing the resources.

@keilw would you mind if I or Magno add a `contributors.txt` file to this `uom-systems` project, simply listing both our names and putting (GlobalMentor, Inc.) in parentheses? Just a simple mention would be fine.

I'll bet you probably have a long list of other contributors to add to the file as well. If you want to note them here, whichever one of us creates the file can add those names, too. (If you have a better place to list contributors, let me know.)

Thanks, and I greatly appreciate your letting us help out!

**Comment by keilw** [comment]
Sure, you are very welcome to be listed. Either we add a contributors file or could mention both of you in one of the POMs (which also gives visibility via the Maven artifacts;-) https://github.com/unitsofmeasurement/uom-systems/blob/master/pom.xml or the UCUM project https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/pom.xml
