### ISSUE TITLE
Problem with dependencies don't let me create quantities properly

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-systems#93]
As already occurred before, some configuration of the projects are making it hard to work when the thing we're working depends on other... For example:
I want to add the new quantities to `systems-quantity` and use them on `systems-ucum-java8`, but even if I change the parent POM of `systems-uom` from:
```
<properties>
		<jdkVersion>1.7</jdkVersion>
		<jsr.version>1.0</jsr.version>
		<ri.version>1.0.3</ri.version>
		<se.version>1.0.5</se.version>
		<si.version>0.6.5</si.version>
		<quantity.version>0.7.0</quantity.version>
		<project.build.javaVersion>${jdkVersion}</project.build.javaVersion>
		<maven.compile.targetLevel>${jdkVersion}</maven.compile.targetLevel>
		<maven.compile.sourceLevel>${jdkVersion}</maven.compile.sourceLevel>
	</properties>
```
to
```
<properties>
		<jdkVersion>1.7</jdkVersion>
		<jsr.version>1.0</jsr.version>
		<ri.version>1.0.3</ri.version>
		<se.version>1.0.5</se.version>
		<si.version>0.6.5</si.version>
		<quantity.version>0.7.1-SNAPSHOT</quantity.version>
		<project.build.javaVersion>${jdkVersion}</project.build.javaVersion>
		<maven.compile.targetLevel>${jdkVersion}</maven.compile.targetLevel>
		<maven.compile.sourceLevel>${jdkVersion}</maven.compile.sourceLevel>
	</properties>
```
something in the hierarchy just don't let me use that SNAPSHOT version... it's like if there's something overriding it to the latest released version, any idea of what it is?

On the last time I created quantities I just kept the units as block of comments to wait until `systems-quantity` was released, but I need to say that it's not good and it might be solved to keep going forward with the project.

**Comment by keilw** [comment]
Using type from https://github.com/unitsofmeasurement/uom-systems/issues/59 as example case

**Comment by keilw** [comment]
This is more a Maven problem. E.g. before pushing a new milestone release like 0.7 the quantity (and parent) has to be published first before pushing and tagging everything. Otherwise please don't forget to call `mvn <some goal> -U` to ensure the snapshots are always refreshed.

**Comment by keilw** [comment]
Just trying this with the new Drag quantity from https://github.com/unitsofmeasurement/uom-systems/issues/59. I only pushed the quantity change first, after it built in CI I should be able to use it and also build everything properly. Somewhere in an overall user or developer guide it might help to mention it. Help with that is greatly appreciated ;-)

**Comment by keilw** [comment]
Just added the new Drag units to the UCUM system plus a special test class. I think it's a good idea to group them by table adding at least the most representative ones for each case. Creation of a quantity and applying it in a unit system should be separate tasks and always run Maven with -U.
