### ISSUE TITLE
NoClassDefFoundError trying to get UCUM formatter.

### ISSUE THREAD

**Issue by garretwilson** [unitsofmeasurement/uom-systems#94]
This morning I tried to updated my client's project to use full UCUM with the release 0.7 release. I included the following dependency:

```xml
<dependency>
  <groupId>systems.uom</groupId>
  <artifactId>systems-ucum-java8</artifactId>
  <version>0.7</version>
</dependency>
```

```java
UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat("UCUM");
```

The result isn't pretty:

```
java.lang.NoClassDefFoundError: Could not initialize class systems.uom.ucum.format.UCUMFormat$Parsing
	at systems.uom.ucum.format.UCUMFormat.getInstance(UCUMFormat.java:108)
	at systems.uom.ucum.internal.UCUMFormatService.<init>(UCUMFormatService.java:53)
	at systems.uom.ucum.internal.UCUMServiceProvider.getUnitFormatService(UCUMServiceProvider.java:54)
```

What is going wrong? Am I missing a dependency? I would have thought `systems-ucum-java8` referenced all its required dependencies.

**Comment by keilw** [comment]
Not sure, how to reproduce that. The name "UCUM" does not seem right, but even for that https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/test/java/systems/uom/ucum/format/UnitFormatServiceTest.java has a test (trying "XYZ") that passes on a `null `assumption.

**Comment by garretwilson** [comment]
I'm using "UCUM" because that's what is shown as an example in JSR 363, and I assumed that's what you would use here.

If not "UCUM", what should I be using as the name of the UCUM `UnitFormat` I want to retrieve from the unit format servce? (I'm just following JSR 363 here, and I had understood that I simply needed the name of the type of `UnitFormat` I needed. I need a UCUM `UnitFormat`, so I asked for one, just like it says in JSR 363.)

**Comment by keilw** [comment]
No, because there are 3 variants for "UCUM". so it's "CI", "CS" or "Print". The JavaDoc just gave an example of a possible String. Probably should put something like "US" or "SI", but it is up to an implementation what is used, so this is just an example not necessarily the exact phrase you may find in a particular implementation.

**Comment by garretwilson** [comment]
That's understandable, but I didn't know what to use.

I'm surprised that you are registering "CI" and "CS". Can't multiple providers be registered? How do I know that I'm requesting a case-sensitive UCUM implementation and not a case-sensitive SI implementation, for example? I would have expected "UCUM-CI" and "UCUM-CS", with "UCUM" returning "UCUM-CS". I mean, "CS" and "CI" don't say anything about UCUM; they seem poor choices for a global registry that could have multiple measurement systems registered.

**Comment by garretwilson** [comment]
There are other issues here:

1. What dependencies should I be using? Is the dependency I provided above sufficient, or must I include others.

2. If "UCUM" isn't a recognized registered unit format type, shouldn't it throw an `IllegalStateException` or something similar, telling me, "Unrecognized unit format type?"

**Comment by keilw** [comment]
Re 1: Please see https://github.com/unitsofmeasurement/uom-demos/tree/master/console/systems/ucum
I can't attach a picture here, but the dependency chain works for systems 0.7 and the underlying si-units 0.6.5 as well as uom-se 1.0.5.
And it returns null for the first getter, the second one with "CS" works fine.

Re 2: No, it is specified in `UnitFormatService`

> Returns the unit format having the specified name or <code>null</code> if none.

**Comment by keilw** [comment]
These are the direct dependencies in the "effective POM"
```
<dependencies>
    <dependency>
      <groupId>systems.uom</groupId>
      <artifactId>systems-quantity</artifactId>
      <version>0.7</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>systems.uom</groupId>
      <artifactId>systems-ucum-java8</artifactId>
      <version>0.7</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```
So at the very least you need system-quantities, the others should come indirectly.

**Comment by garretwilson** [comment]
> So at the very least you need system-quantities, the others should come indirectly.

So that was the source of one problem, I think. I see in the POM that you marked it as "provided", requiring me to include it explicitly. I'm curious as to why that is.

**Comment by keilw** [comment]
Not sure, I believe it was an attempt to get it built and used as the latest version on the fly (e.g. if you add new quantities) but it does not seem to have that effect. We can remove it for the next update of systems.

**Comment by garretwilson** [comment]
> I would have expected "UCUM-CI" and "UCUM-CS" ...

I may have been under a misunderstanding of the granularity of service registration; see discussion in #95.

**Comment by keilw** [comment]
`getUnitFormat(String)` supports aliasing, so using both "CI" and "UCUM-CI" should be possible.

It may be lesser priority, but please file an issue for such alias, too
