### ISSUE TITLE
Verify only ASCII characters used in UCUM resources

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#98]
http://unitsofmeasure.org/ucum.html#section-Character-Set-and-Lexical-Rules of the UCUM specification declares, that
> All expressions of The Unified Code for Units of Measure shall be built from characters of the 7-bit US-ASCII character set exclusively

It remains to be clarified, if `Print` characters also fall under that restriction, but all others must be ASCII characters only. No UTF-8 or wider Unicode.

**Comment by garretwilson** [comment]
> No UTF-8 or wider Unicode.

I'm not sure what you mean by that; UTF-8 is an encoding mechanism, not a character set (although it does use the Unicode character set). And all ASCII characters are also Unicode characters of course. Perhaps you meant "No ISO-88591-1 or higher Unicode code points."

Sorry to be pedantic; just trying to help.

**Comment by keilw** [comment]
Wider Unicode. Yes, There is a helper mehthod `isAllASCII()` in `SimpleUnitFormat`.  We should make sure, that either it or a similar method (at least at design time) passes for all resources in question.

**Comment by keilw** [comment]
Some Print symbols look like they have higher code points, but CI and CS are ASCII only.
