### ISSUE TITLE
Build doesn't fail when some of the tests fails

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-systems#99]
Although you might have done it to make it easier to you @keilw, or maybe it came from JScience, Idk.. this doesn't help anything for other developers, and this even disturbs me when I try to build something that is broken and it "builds successfully", maybe we should try to keep it on the default way. A build that fails on Maven is important to look for bugs, for tests that weren't created correctly and helps to fix them.

Maybe you should consider changing this property or whatever it is, to make it work like all the other projects does.

**Comment by keilw** [comment]
@magnonasc JScience does not have a CI server I know of. At least the API, RI and uom-se require that every JUnit test passes. If the build does not end up broken for many weeks it could be changed, but I get annoying mails by CircleCI and as of now there is no way to silence it ;-/

**Comment by magnonasc** [comment]
I don't understand, why do you use CircleCI so, if you'll cheat the tests?

**Comment by garretwilson** [comment]
We need to know if the build is failing. If you have some continuous integration system (I haven't looked closely at the POMs) that sends annoying emails if the build is broken, so much the better. We don't want the build to be broken.

If there is some particular issue with some test that is failing and cannot be immediately fixed, it can easily be ignored by adding an `@Ignore` annotation in JUnit. It seems rather drastic to simply say, "just let all errors go on by". The tests are there for a reason. It _should_ annoy us when the build is broken --- that is better than being annoyed when a broken build is released and we don't realize until afterwards that it is broken.

**Comment by keilw** [comment]
Then let's see if @magnonasc or others can help to find a printing solution. If they fail too long @Ignore is always an option. Very few tests are ignored and API or RI have a decent test coverage (not sure about this module)

**Comment by keilw** [comment]
@magnonasc It is not a question of CircleCI, TravisCI or others, they all send notifications to some people in the team (at the very least the one who created the build)

**Comment by keilw** [comment]
@garretwilson, @magnonasc please feel free to join CircleCI, you don't show as following builds under https://circleci.com/team. It has a fairly powerful notification, I follow all projects by defult, but if necessary I could also ignore some or leave it to others to observe them ;-)

**Comment by garretwilson** [comment]
@keilw We may be saying different things here. If I build the project locally using `mvn clean install`, for example, if there is a failing test the build should fail. That's standard Maven practice. If this doesn't happen, and if the library is built and is installed, I would have no idea that there was a problem unless every time I did a build I pored over every line in the output. But there's no point in needing to do that --- that's why Maven standard practice is to fail the build if a test fails, and that's what developers expect.

I'm not sure where CircleCI or TravisCI or Bamboo affects this conclusion. If you don't want CircleCI (I've never used it) to tell you when the build fails, can't you unsubscribe from it --- or stop using it? By turning off errors aren't you defeating the purpose of a continuous integration system.

(I haven't looked into exactly where or how you turned off errors in the build.)

**Comment by keilw** [comment]
@garretwilson Please see some of the other repositories like unit-api, etc. I also don't have 6-900 lines of POM in my head, but that's been set in the underlying "core" elements of the JSR and project where necessary.

**Comment by desruisseaux** [comment]
@keilw I agree with the other comments that if a test fails, then the Maven build shall fail unless instructed otherwise. If someone wish to keep the build running despite test failures, he can specify the `--fail-never` option to Maven.

**Comment by keilw** [comment]
@desruisseaux Thanks for the input. Can you as the most senior EG member also contribute to the questions and discussion about the underlying issue https://github.com/unitsofmeasurement/uom-systems/issues/97 ?

**Comment by keilw** [comment]
It is based on the uom-parent POM. Which was initially derived from JSR 354 parent (with the same behavior). AFAIK if nothing is set, Surefire may also ignore it, but now the latest uom-parent (have to use 1.0.4-SNAPSHOT or above) by default does not ignore JUnit/Surefire failures and the overall build fails if a single test fails.
